name: Publish Annotations

on:
  push:
    tags:
      - 'annotations/*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag
        id: extract
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"      

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./artifacts ./Sources/Annotations/Annotations.csproj

      - name: Publish NuGet package
        run: |          
          PACKAGE_VERSION=$(echo ${{ steps.extract.outputs.tag }} | cut -d/ -f2)
          if [ -n "$PACKAGE_VERSION" ]; then
          dotnet nuget push ./artifacts/P3Model.Annotations.${PACKAGE_VERSION}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          fi
